import { describe, it, expect } from "vitest";
import {
  UnsupportedSqliteSql,
  primaryKeyColumns,
  translateSqliteToPg,
} from "@/lib/db/dialect/sqliteToPg.js";

describe("primaryKeyColumns", () => {
  it("reads single-column PRIMARY KEY from TABLES", () => {
    expect(primaryKeyColumns("providerConnections")).toEqual(["id"]);
    expect(primaryKeyColumns("usageDaily")).toEqual(["dateKey"]);
    expect(primaryKeyColumns("settings")).toEqual(["id"]);
    expect(primaryKeyColumns("usageHistory")).toEqual(["id"]);
  });

  it("reads composite PRIMARY KEY from TABLES", () => {
    expect(primaryKeyColumns("kv")).toEqual(["scope", "key"]);
  });

  it("returns null for unknown tables", () => {
    expect(primaryKeyColumns("nope")).toBeNull();
  });
});

describe("translateSqliteToPg", () => {
  it("rewrites ? placeholders outside strings", () => {
    const { kind, text } = translateSqliteToPg(
      `SELECT * FROM apiKeys WHERE id = ? AND name = ?`,
    );
    expect(kind).toBe("sql");
    expect(text).toContain("$1");
    expect(text).toContain("$2");
    expect(text).not.toContain("?");
  });

  it("does not rewrite ? inside strings", () => {
    const { text } = translateSqliteToPg(`SELECT '?' as q`);
    expect(text).toContain("'?'");
    expect(text).not.toMatch(/\$1/);
  });

  it("quotes camelCase identifiers", () => {
    const { text } = translateSqliteToPg(
      `SELECT createdAt, promptTokens FROM usageHistory WHERE connectionId = ?`,
    );
    expect(text).toContain(`"createdAt"`);
    expect(text).toContain(`"promptTokens"`);
    expect(text).toContain(`"usageHistory"`);
    expect(text).toContain(`"connectionId"`);
    expect(text).toContain("$1");
  });

  it("rewrites INSERT OR REPLACE using table PK", () => {
    const { text } = translateSqliteToPg(
      `INSERT OR REPLACE INTO apiKeys(id, key, name, machineId, isActive, createdAt) VALUES(?, ?, ?, ?, ?, ?)`,
    );
    expect(text).toMatch(/INSERT INTO "apiKeys"/);
    expect(text).toMatch(/ON CONFLICT\(id\) DO UPDATE SET/);
    expect(text).toContain(`key = EXCLUDED.key`);
    expect(text).not.toMatch(/id = EXCLUDED/);
    expect(text).toContain("$1");
  });

  it("rewrites INSERT OR REPLACE for composite kv PK", () => {
    const { text } = translateSqliteToPg(
      `INSERT OR REPLACE INTO kv(scope, key, value) VALUES(?, ?, ?)`,
    );
    expect(text).toMatch(/ON CONFLICT\(scope, key\) DO UPDATE SET value = EXCLUDED.value/);
  });

  it("rewrites INSERT OR IGNORE", () => {
    const { text } = translateSqliteToPg(
      `INSERT OR IGNORE INTO kv(scope, key, value) VALUES(?, ?, ?)`,
    );
    expect(text).toMatch(/INSERT INTO kv/);
    expect(text).toMatch(/ON CONFLICT DO NOTHING/);
  });

  it("rewrites AUTOINCREMENT and REAL in DDL", () => {
    const { text } = translateSqliteToPg(
      `CREATE TABLE IF NOT EXISTS usageHistory (id INTEGER PRIMARY KEY AUTOINCREMENT, cost REAL DEFAULT 0, timestamp TEXT NOT NULL)`,
    );
    expect(text).toContain(`INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`);
    expect(text).not.toMatch(/AUTOINCREMENT/i);
    expect(text).toContain(`DOUBLE PRECISION`);
    expect(text).toContain(`"usageHistory"`);
  });

  it("rewrites json_extract for a single key", () => {
    const { text } = translateSqliteToPg(
      `SELECT json_extract(data, '$.tokens') AS tokens FROM requestDetails`,
    );
    expect(text).toMatch(/\(data::json ->> 'tokens'\)/);
    expect(text).toContain(`"requestDetails"`);
  });

  it("maps PRAGMA table_info to a special kind", () => {
    expect(translateSqliteToPg(`PRAGMA table_info(providerConnections)`)).toEqual({
      kind: "pragma_table_info",
      table: "providerConnections",
    });
  });

  it("maps other PRAGMA to noop", () => {
    expect(translateSqliteToPg(`PRAGMA journal_mode = WAL`).kind).toBe("pragma_noop");
  });

  it("maps sqlite_master to a special kind", () => {
    expect(translateSqliteToPg(
      `SELECT name, sql FROM main.sqlite_master WHERE type='table'`,
    ).kind).toBe("sqlite_master");
  });

  it("maps ATTACH/DETACH to skip_backup", () => {
    expect(translateSqliteToPg(`ATTACH DATABASE 'x' AS bak`).kind).toBe("skip_backup");
    expect(translateSqliteToPg(`DETACH DATABASE bak`).kind).toBe("skip_backup");
  });

  it("throws on datetime() / strftime() / json_each / nested json_extract", () => {
    expect(() => translateSqliteToPg(`SELECT datetime('now')`)).toThrow(UnsupportedSqliteSql);
    expect(() => translateSqliteToPg(`SELECT strftime('%Y', timestamp)`)).toThrow(UnsupportedSqliteSql);
    expect(() => translateSqliteToPg(`SELECT json_each(data)`)).toThrow(UnsupportedSqliteSql);
    expect(() => translateSqliteToPg(`SELECT json_extract(data, '$.a.b')`)).toThrow(UnsupportedSqliteSql);
  });

  it("throws INSERT OR REPLACE for unknown tables", () => {
    expect(() => translateSqliteToPg(`INSERT OR REPLACE INTO ghosts(id) VALUES(?)`)).toThrow(UnsupportedSqliteSql);
  });
});
