import { TABLES } from "../schema.js";

export class UnsupportedSqliteSql extends Error {
  constructor(sql, reason) {
    super(`[DB][pg] Unsupported SQLite SQL (${reason}): ${sql}`);
    this.name = "UnsupportedSqliteSql";
    this.sql = sql;
    this.reason = reason;
  }
}

export function primaryKeyColumns(tableName) {
  const def = TABLES[tableName];
  if (!def) return null;
  if (def.primaryKey) {
    const m = def.primaryKey.match(/PRIMARY KEY\s*\(([^)]+)\)/i);
    if (m) return m[1].split(",").map((s) => s.trim());
  }
  for (const [col, spec] of Object.entries(def.columns)) {
    if (/\bPRIMARY KEY\b/i.test(spec)) return [col];
  }
  return null;
}

function splitStrings(sql) {
  const parts = [];
  let i = 0;
  let buf = "";
  let inStr = false;
  while (i < sql.length) {
    const ch = sql[i];
    if (inStr) {
      buf += ch;
      if (ch === "'" && sql[i + 1] === "'") {
        buf += sql[i + 1];
        i += 2;
        continue;
      }
      if (ch === "'") {
        parts.push({ type: "str", text: buf });
        buf = "";
        inStr = false;
      }
      i++;
      continue;
    }
    if (ch === "'") {
      if (buf) parts.push({ type: "code", text: buf });
      buf = "'";
      inStr = true;
      i++;
      continue;
    }
    buf += ch;
    i++;
  }
  if (buf) parts.push({ type: inStr ? "str" : "code", text: buf });
  return parts;
}

function mapCodeAndStrings(sql, mapCode) {
  return splitStrings(sql).map((p) => (p.type === "code" ? { ...p, text: mapCode(p.text) } : p))
    .map((p) => p.text)
    .join("");
}

function rewriteInsertOrReplace(sql) {
  return sql.replace(
    /INSERT\s+OR\s+REPLACE\s+INTO\s+([A-Za-z_][\w]*)\s*\(([^)]+)\)\s*VALUES\s*\(/gi,
    (full, table, cols, offset, whole) => {
      const pk = primaryKeyColumns(table);
      if (!pk) throw new UnsupportedSqliteSql(whole, `INSERT OR REPLACE unknown table ${table}`);
      return `INSERT INTO ${table}(${cols}) __OR_REPLACE__${table}__ VALUES(`;
    },
  );
}

function finalizeOrReplace(sql) {
  return sql.replace(
    /INSERT INTO ([A-Za-z_][\w]*)\(([^)]+)\) __OR_REPLACE__\1__ VALUES\(([\s\S]*)\)(\s*;?\s*)$/i,
    (full, table, cols, values, tail) => {
      const pk = primaryKeyColumns(table);
      const colList = cols.split(",").map((c) => c.trim()).filter(Boolean);
      const nonPk = colList.filter((c) => !pk.includes(c));
      const pkList = pk.join(", ");
      if (!nonPk.length) {
        return `INSERT INTO ${table}(${cols}) VALUES(${values}) ON CONFLICT(${pkList}) DO NOTHING${tail}`;
      }
      const set = nonPk.map((c) => `${c} = EXCLUDED.${c}`).join(", ");
      return `INSERT INTO ${table}(${cols}) VALUES(${values}) ON CONFLICT(${pkList}) DO UPDATE SET ${set}${tail}`;
    },
  );
}

function applyInsertOrIgnore(sql) {
  const re = /INSERT\s+OR\s+IGNORE\s+INTO\s+([A-Za-z_][\w]*)\s*\(([^)]+)\)\s*VALUES\s*\(([\s\S]*?)\)(\s*;?\s*)$/i;
  const m = sql.match(re);
  if (!m) {
    const re2 = /INSERT\s+OR\s+IGNORE\s+INTO\s+/i;
    if (!re2.test(sql)) return sql;
    return sql.replace(re2, "INSERT INTO ") + " ON CONFLICT DO NOTHING";
  }
  return `INSERT INTO ${m[1]}(${m[2]}) VALUES(${m[3]}) ON CONFLICT DO NOTHING${m[4] || ""}`;
}

function rewriteDdl(sql) {
  return sql
    .replace(/INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/\bREAL\b/gi, "DOUBLE PRECISION");
}

function rewriteJsonExtract(sql) {
  let out = sql.replace(
    /json_valid\s*\(\s*([A-Za-z_][\w]*)\s*\)/gi,
    "TRUE",
  );
  return out.replace(
    /json_extract\s*\(\s*([A-Za-z_][\w]*)\s*,\s*'\$\.([^']+)'\s*\)/gi,
    (full, col, path) => {
      if (path.includes(".") || path.includes("[") || path.includes("]")) {
        throw new UnsupportedSqliteSql(sql, "nested json_extract path");
      }
      return `(${col}::json ->> '${path}')`;
    },
  );
}

const SQL_KEYWORDS = new Set([
  "SELECT", "INSERT", "UPDATE", "DELETE", "FROM", "WHERE", "AND", "OR", "NOT", "NULL",
  "INTO", "VALUES", "SET", "ON", "CONFLICT", "DO", "AS", "ORDER", "BY", "DESC", "ASC",
  "LIMIT", "OFFSET", "CREATE", "TABLE", "INDEX", "IF", "EXISTS", "PRIMARY", "KEY",
  "INTEGER", "TEXT", "DEFAULT", "CHECK", "UNIQUE", "INNER", "JOIN", "LEFT", "RIGHT",
  "GROUP", "HAVING", "DISTINCT", "COUNT", "MAX", "MIN", "SUM", "AVG", "COALESCE",
  "IN", "IS", "BETWEEN", "LIKE", "CAST", "CASE", "WHEN", "THEN", "ELSE", "END",
  "BEGIN", "COMMIT", "ROLLBACK", "SAVEPOINT", "RELEASE", "ALTER", "ADD", "COLUMN",
  "DROP", "WITH", "UNION", "ALL", "EXCLUDED", "RETURNING", "GENERATED", "IDENTITY",
  "DOUBLE", "PRECISION", "BOOLEAN", "TRUE", "FALSE", "CONSTRAINT", "REFERENCES",
  "FOREIGN", "CASCADE", "RESTRICT", "NOTHING", "REPLACE", "IGNORE", "VACUUM",
  "ANALYZE", "EXPLAIN", "USING", "RETURNING", "OVER", "PARTITION", "WINDOW",
  "CURRENT", "ROW", "ROWS", "UNBOUNDED", "PRECEDING", "FOLLOWING", "FILTER",
  "JSON", "JSONB", "TYPE", "MAIN", "TEMP", "TEMPORARY", "VIEW", "TRIGGER",
  "PROCEDURE", "FUNCTION", "RETURNS", "LANGUAGE", "IMMUTABLE", "STABLE",
  "VOLATILE", "STRICT", "SCHEMA", "PUBLIC", "AUTHORIZATION", "GRANT", "REVOKE",
  "TO", "USER", "ROLE", "WITH", "WITHOUT", "ROWID", "AUTOINCREMENT",
]);

function quoteCamelCase(code) {
  return code.replace(/\b([A-Za-z_][A-Za-z0-9_]*)\b/g, (ident) => {
    if (!/[A-Z]/.test(ident)) return ident;
    if (SQL_KEYWORDS.has(ident.toUpperCase()) && ident === ident.toUpperCase()) return ident;
    return `"${ident}"`;
  });
}

function rewritePlaceholders(sql) {
  let n = 0;
  return mapCodeAndStrings(sql, (code) => code.replace(/\?/g, () => `$${++n}`));
}

function rejectUnsupported(sql) {
  const lower = sql.toLowerCase();
  if (/\bdatetime\s*\(/.test(lower)) throw new UnsupportedSqliteSql(sql, "datetime()");
  if (/\bstrftime\s*\(/.test(lower)) throw new UnsupportedSqliteSql(sql, "strftime()");
  if (/\bjson_each\s*\(/.test(lower)) throw new UnsupportedSqliteSql(sql, "json_each()");
}

export function translateSqliteToPg(sql) {
  const trimmed = String(sql).trim();
  rejectUnsupported(trimmed);

  const pragmaInfo = trimmed.match(/^PRAGMA\s+table_info\s*\(\s*([A-Za-z_][\w]*)\s*\)\s*;?$/i);
  if (pragmaInfo) return { kind: "pragma_table_info", table: pragmaInfo[1] };
  if (/^PRAGMA\b/i.test(trimmed)) return { kind: "pragma_noop" };

  if (/\bsqlite_master\b/i.test(trimmed)) return { kind: "sqlite_master" };
  if (/^\s*ATTACH\s+DATABASE\b/i.test(trimmed) || /^\s*DETACH\s+DATABASE\b/i.test(trimmed)) {
    return { kind: "skip_backup" };
  }

  let out = trimmed;
  out = rewriteJsonExtract(out);
  out = applyInsertOrIgnore(out);
  out = rewriteInsertOrReplace(out);
  out = finalizeOrReplace(out);
  // leftover marker means VALUES parsing failed
  if (/__OR_REPLACE__/.test(out)) {
    throw new UnsupportedSqliteSql(sql, "INSERT OR REPLACE rewrite failed");
  }
  out = rewriteDdl(out);
  out = mapCodeAndStrings(out, quoteCamelCase);
  out = rewritePlaceholders(out);
  return { kind: "sql", text: out };
}
